from datetime import datetime, timezone
from typing import Any, Literal

from pydantic import Field

from digitalkin.models.module import UtilityProtocol
from digitalkin.models.module.utility.default import ServiceHealthStatus


class EndOfStreamOutputPayload(UtilityProtocol):
    """Signal that the stream has ended."""

    protocol: Literal["end_of_stream"] = "end_of_stream"  # type: ignore[misc]


class ModuleStartInfoOutputPayload(UtilityProtocol):
    """Output sent when module starts with execution context.

    This protocol is sent as the first message when a module starts,
    providing the client with essential execution context information.
    """

    protocol: Literal["module_start_info"] = "module_start_info"  # type: ignore[misc]
    job_id: str = Field(..., description="Unique job identifier")
    mission_id: str = Field(..., description="Mission identifier")
    setup_id: str = Field(..., description="Setup identifier")
    setup_version_id: str = Field(..., description="Setup version identifier")
    module_id: str = Field(..., description="Module identifier")
    module_name: str = Field(..., description="Human-readable module name")
    started_at: str = Field(
        default_factory=lambda: datetime.now(tz=timezone.utc).isoformat(),
        description="ISO timestamp when module started",
    )


class HealthcheckPingOutputPayload(UtilityProtocol):
    """Output for healthcheck ping response.

    Simple alive check that returns "pong" status.
    """

    protocol: Literal["healthcheck_ping"] = "healthcheck_ping"  # type: ignore[misc]
    status: Literal["pong"] = "pong"
    latency_ms: float | None = Field(
        default=None,
        description="Round-trip latency in milliseconds",
    )


class HealthcheckServicesOutputPayload(UtilityProtocol):
    """Output for healthcheck services response.

    Reports the health status of all configured services.
    """

    protocol: Literal["healthcheck_services"] = "healthcheck_services"  # type: ignore[misc]
    services: list[ServiceHealthStatus] = Field(
        ...,
        description="List of service health statuses",
    )
    overall_status: Literal["healthy", "degraded", "unhealthy"] = Field(
        ...,
        description="Overall health status based on all services",
    )


class HealthcheckStatusOutputPayload(UtilityProtocol):
    """Output for healthcheck status response.

    Comprehensive module status including uptime, active jobs, and metadata.
    """

    protocol: Literal["healthcheck_status"] = "healthcheck_status"  # type: ignore[misc]
    module_name: str = Field(..., description="Name of the module")
    module_status: str = Field(..., description="Current status of the module")
    uptime_seconds: float | None = Field(
        default=None,
        description="Module uptime in seconds",
    )
    active_jobs: int = Field(
        default=0,
        description="Number of currently active jobs",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata about the module",
    )


class MessageOutputPayload(UtilityProtocol):
    """Output payload for message trigger."""

    protocol: Literal["message"] = "message"
    user_response: str = Field(
        ...,
        title="User Response",
        description="The response generated by the assistant based on the user prompt.",
    )
