"""Human-in-the-loop (HITL) runner for Agno agents with AG-UI frontend tools.

This module provides the high-level glue to build an Agno-powered module
that supports AG-UI *frontend tools* — tools declared by the AG-UI client
and executed on the front rather than on the agent process. The flow is:

1. The front sends ``RunAgentInput`` with a ``tools`` list.
2. The LLM calls one of those tools.
3. Agno emits ``RunPausedEvent`` (its HITL signal) and freezes the run.
4. We persist the paused :class:`~agno.run.agent.RunOutput` via the
   module's :class:`~digitalkin.services.storage.StorageStrategy`, keyed by
   ``thread_id``.
5. We emit an AG-UI ``RunFinished`` with
   ``result={"status": "awaiting_tool_result", "pending_tool_call_ids": [...]}``
   so the front knows to execute the tool and reply.
6. On the next ``RunAgentInput`` carrying a matching ``ToolMessage``, we
   load the paused run, inject the result into the corresponding
   :class:`~agno.run.requirement.RunRequirement`, and resume via
   :meth:`~agno.agent.Agent.acontinue_run`.

The design keeps the process stateless (every replica can resume any
thread) because all the state lives in the storage service.

Typical usage inside a module trigger::

    from digitalkin.community.agno import (
        AgnoHitlRunner,
        HITL_STORAGE_CONFIG,
        make_tools_factory,
    )

    # In your Module class — register the storage schema
    services_config_params = {
        "storage": {
            "config": {
                **HITL_STORAGE_CONFIG,
                "agno_sessions": AgnoSession,
                ...
            },
            ...
        },
        ...
    }

    # In your agent factory
    agent = Agent(
        tools=make_tools_factory([MyBaseToolkit()]),
        cache_callables=False,
        ...
    )

    # In your trigger handler
    runner = AgnoHitlRunner(agent=agent, storage=context.storage)
    pause_info = await runner.handle_agui_input(
        input_data=input_data,
        send=send,
        context=context,        # enables auto-emission of awaiting RunFinished
    )

``handle_agui_input`` will figure out whether this is a fresh user
message, a resume of a paused run, or an abandon (new user message while
a tool was pending) and dispatch accordingly.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field

if TYPE_CHECKING:
    from collections.abc import Callable, Coroutine

    from ag_ui.core.types import Message as AgUiMessage
    from ag_ui.core.types import Tool as AgUiTool
    from agno.agent import Agent
    from agno.run.agent import RunOutput

    from digitalkin.models.events import BaseAgentRunEvent
    from digitalkin.models.module import ModuleContext
    from digitalkin.services.storage import StorageStrategy

logger = logging.getLogger(__name__)

_PAUSED_RUNS_COLLECTION = "paused_runs"
_AWAITING_STATUS = "awaiting_tool_result"


# ── Storage schema ──────────────────────────────────────────────────────────


class PausedRunRecord(BaseModel):
    """Persistent snapshot of an Agno run paused on external tool execution.

    Stored in the ``paused_runs`` collection keyed by ``thread_id``. The
    ``payload`` field holds ``RunOutput.to_dict()`` verbatim so
    :meth:`agno.run.agent.RunOutput.from_dict` can round-trip the run on
    any replica when the front replies with the tool result(s).
    """

    model_config = ConfigDict(extra="allow")

    thread_id: str
    run_id: str
    pending_tool_call_ids: list[str] = Field(default_factory=list)
    payload: dict[str, Any] = Field(default_factory=dict, description="RunOutput.to_dict()")


HITL_STORAGE_CONFIG: dict[str, type[BaseModel]] = {_PAUSED_RUNS_COLLECTION: PausedRunRecord}
"""Drop-in storage config fragment — merge into your module's ``services_config_params``.

Example::

    services_config_params = {
        "storage": {
            "config": {**HITL_STORAGE_CONFIG, "my_other_collection": MyModel},
            ...
        },
    }
"""


# ── Return type ─────────────────────────────────────────────────────────────


@dataclass
class PauseInfo:
    """Summary of a paused Agno run.

    Returned by :meth:`AgnoHitlRunner.run` and related methods whenever
    the run paused on one or more external tool calls. Callers typically
    use it to emit the AG-UI awaiting-tool-result event to the front.

    ``new_messages`` carries the AG-UI messages generated by Agno during
    the paused run (user echoes, the assistant message with ``tool_calls``,
    and any tool results emitted before the pause). It's provided because
    Agno does not emit stream events from which the front can reconstruct
    the assistant-with-tool-calls message — in particular, when the LLM
    goes straight from reasoning to a frontend tool call without emitting
    any text. Consumers typically push these messages to the front via a
    :class:`~ag_ui.core.events.MessagesSnapshotEvent` so the client has an
    authoritative view of the conversation.
    """

    thread_id: str
    run_id: str
    pending_tool_call_ids: list[str]
    new_messages: list[AgUiMessage] = field(default_factory=list)


# ── Storage wrapper ─────────────────────────────────────────────────────────


class PausedRunStore:
    """Thin wrapper around :class:`StorageStrategy` for the ``paused_runs`` collection.

    Owns serialization of :class:`~agno.run.agent.RunOutput` and keying by
    ``thread_id``. Instances are cheap — create one per trigger handler.
    """

    COLLECTION: ClassVar[str] = _PAUSED_RUNS_COLLECTION

    def __init__(self, storage: StorageStrategy) -> None:
        """Initialize the store.

        Args:
            storage: The module's storage strategy. The collection
                ``paused_runs`` must be registered with
                :class:`PausedRunRecord` — use :data:`HITL_STORAGE_CONFIG`.
        """
        self._storage = storage

    async def save(self, run_output: RunOutput, thread_id: str) -> PauseInfo:
        """Serialize and store a paused ``RunOutput``.

        Args:
            run_output: The paused Agno run (``is_paused=True`` with
                populated ``requirements``).
            thread_id: AG-UI thread identifier (the record key).

        Returns:
            A :class:`PauseInfo` describing what was persisted.
        """
        # Extract pending tool_call_ids from run_output.tools (not requirements).
        # Agno's requirements list may be incomplete: it only appends a
        # RunRequirement for the LAST tool in each paused batch
        # (tool_executions_list[-1] in _response.py), so when N external tools
        # pause in the same turn, only the last one gets a requirement.
        # run_output.tools contains ALL tools (server-side + external), so we
        # filter by external_execution_required and deduplicate.
        seen: set[str] = set()
        pending: list[str] = []
        for tool in run_output.tools or []:
            tid = getattr(tool, "tool_call_id", None)
            if tid and tid not in seen and getattr(tool, "external_execution_required", False):
                seen.add(tid)
                pending.append(tid)
        record = PausedRunRecord(
            thread_id=thread_id,
            run_id=run_output.run_id or "",
            pending_tool_call_ids=pending,
            payload=run_output.to_dict(),
        )
        await self._storage.upsert(
            collection=self.COLLECTION,
            record_id=thread_id,
            data=record.model_dump(),
        )
        logger.info(
            "PausedRunStore: saved thread_id=%s run_id=%s pending=%s",
            thread_id,
            record.run_id,
            pending,
        )
        return PauseInfo(
            thread_id=thread_id,
            run_id=record.run_id,
            pending_tool_call_ids=pending,
        )

    async def load(self, thread_id: str) -> PausedRunRecord | None:
        """Fetch the paused run record for a thread.

        Args:
            thread_id: AG-UI thread identifier.

        Returns:
            The :class:`PausedRunRecord` if one exists, otherwise ``None``.
        """
        record = await self._storage.read(collection=self.COLLECTION, record_id=thread_id)
        if record is None:
            return None
        return PausedRunRecord.model_validate(record.data)

    async def delete(self, thread_id: str) -> None:
        """Remove the paused run record for a thread."""
        await self._storage.remove(collection=self.COLLECTION, record_id=thread_id)


# ── Agno → AG-UI message conversion ────────────────────────────────────────


def _agno_messages_to_agui(agno_messages: list[Any]) -> list[AgUiMessage]:
    """Convert ``agno.models.message.Message`` instances into AG-UI messages.

    Drops system/developer/reasoning messages (which the front should not
    receive) and normalizes the rest. Assistant messages carry their
    ``tool_calls`` list reshaped into AG-UI :class:`~ag_ui.core.types.ToolCall`
    objects; tool messages keep their ``tool_call_id`` + ``content`` pair.

    Args:
        agno_messages: Value of ``RunOutput.messages`` at pause time.

    Returns:
        A list of AG-UI :class:`~ag_ui.core.types.Message` instances ready
        to be embedded in a :class:`~ag_ui.core.events.MessagesSnapshotEvent`.
    """
    from ag_ui.core.types import (
        AssistantMessage as AgUiAssistantMessage,
    )
    from ag_ui.core.types import (
        FunctionCall as AgUiFunctionCall,
    )
    from ag_ui.core.types import (
        ToolCall as AgUiToolCall,
    )
    from ag_ui.core.types import (
        ToolMessage as AgUiToolMessage,
    )
    from ag_ui.core.types import (
        UserMessage as AgUiUserMessage,
    )

    result: list[AgUiMessage] = []
    for msg in agno_messages or []:
        role = getattr(msg, "role", None)
        msg_id = getattr(msg, "id", None) or ""
        content = getattr(msg, "content", None)
        # Agno content may be a list of parts for multimodal — stringify for AG-UI
        if isinstance(content, list):
            content = " ".join(str(part) for part in content if part is not None)

        if role == "user":
            result.append(AgUiUserMessage(id=msg_id, role="user", content=content or ""))
        elif role == "assistant":
            raw_calls = getattr(msg, "tool_calls", None) or []
            agui_tool_calls: list[AgUiToolCall] = []
            for tc in raw_calls:
                # Agno stores tool_calls as dicts shaped like the OpenAI API.
                tc_id = tc.get("id") if isinstance(tc, dict) else getattr(tc, "id", None)
                func = tc.get("function") if isinstance(tc, dict) else getattr(tc, "function", None)
                if not tc_id or func is None:
                    continue
                func_name = func.get("name") if isinstance(func, dict) else getattr(func, "name", None)
                func_args = func.get("arguments") if isinstance(func, dict) else getattr(func, "arguments", None)
                if not isinstance(func_args, str):
                    func_args = json.dumps(func_args) if func_args is not None else "{}"
                agui_tool_calls.append(
                    AgUiToolCall(
                        id=tc_id,
                        type="function",
                        function=AgUiFunctionCall(name=func_name or "", arguments=func_args),
                    )
                )
            result.append(
                AgUiAssistantMessage(
                    id=msg_id,
                    role="assistant",
                    content=content if isinstance(content, str) else None,
                    tool_calls=agui_tool_calls or None,
                )
            )
        elif role == "tool":
            tool_call_id = getattr(msg, "tool_call_id", None)
            if not tool_call_id:
                continue
            result.append(
                AgUiToolMessage(
                    id=msg_id,
                    role="tool",
                    tool_call_id=tool_call_id,
                    content=content if isinstance(content, str) else "",
                )
            )
        # system / developer / reasoning → dropped (not meant for the client)
    return result


# ── AG-UI convenience ───────────────────────────────────────────────────────


async def emit_messages_snapshot(
    context: ModuleContext,
    messages: list[AgUiMessage],
) -> None:
    """Emit an AG-UI ``MessagesSnapshot`` event.

    Typically called just before :func:`emit_awaiting_tool_result` on a
    paused run so the front has an authoritative view of the conversation
    (including the assistant message carrying the frontend ``tool_calls``,
    which cannot be reconstructed from the streamed tool-call events alone).

    Args:
        context: Current module context.
        messages: List of AG-UI messages, typically produced by
            :func:`_agno_messages_to_agui` from ``RunOutput.messages``.
    """
    if not messages:
        return

    from ag_ui.core.events import MessagesSnapshotEvent as AgUiMessagesSnapshotEvent

    from digitalkin.models.module.ag_ui import (
        AgUiMessagesSnapshotOutput,
        AgUiOutput,
    )

    output = AgUiOutput(
        root=AgUiMessagesSnapshotOutput(
            event=AgUiMessagesSnapshotEvent(messages=messages),
        )
    )
    await context.callbacks.send_message(output)
    logger.info("emit_messages_snapshot: sent %d message(s)", len(messages))


async def emit_awaiting_tool_result(
    context: ModuleContext,
    *,
    thread_id: str,
    run_id: str,
    pending_tool_call_ids: list[str],
) -> None:
    """Emit an AG-UI ``RunFinished`` with ``status="awaiting_tool_result"``.

    This is the protocol signal telling the front "the run paused on a
    client-side tool; execute it and reply with a ``ToolMessage``". It
    goes out via ``context.callbacks.send_message`` (bypassing the
    standard :class:`~digitalkin.mixins.agui_mixin.AgUiMixin` event
    mapping, which has no notion of an "awaiting" status).

    Args:
        context: Current module context.
        thread_id: AG-UI thread identifier.
        run_id: Run identifier to echo back in the finished event.
        pending_tool_call_ids: The ``tool_call_id`` values the front must
            execute and resolve — echoed in ``result.pending_tool_call_ids``
            so the front can match them.
    """
    from ag_ui.core.events import RunFinishedEvent as AgUiRunFinishedEvent

    from digitalkin.models.module.ag_ui import (
        AgUiOutput,
        AgUiRunFinishedOutput,
    )

    output = AgUiOutput(
        root=AgUiRunFinishedOutput(
            event=AgUiRunFinishedEvent(
                thread_id=thread_id,
                run_id=run_id,
                result={
                    "status": _AWAITING_STATUS,
                    "pending_tool_call_ids": pending_tool_call_ids,
                },
            )
        )
    )
    await context.callbacks.send_message(output)
    logger.info(
        "emit_awaiting_tool_result: thread_id=%s pending=%s",
        thread_id,
        pending_tool_call_ids,
    )


# ── Main runner ─────────────────────────────────────────────────────────────


class AgnoHitlRunner:
    """High-level runner for an Agno agent with AG-UI frontend-tool support.

    Wraps a configured :class:`~agno.agent.Agent` and a
    :class:`PausedRunStore`, and exposes three levels of API:

    - :meth:`run` / :meth:`continue_paused_run` — low-level: stream one
      Agno run (fresh or resumed) and return a :class:`PauseInfo` if it
      paused on an external tool.
    - :meth:`try_resume` — inspects an AG-UI input and resumes iff a
      matching :class:`~ag_ui.core.types.ToolMessage` is present.
    - :meth:`handle_agui_input` — all-in-one: detects resume vs fresh
      message, dispatches, and (optionally) emits the awaiting
      ``RunFinished`` event on pause. Use this one from a trigger.
    """

    def __init__(
        self,
        *,
        agent: Agent,
        storage: StorageStrategy | None = None,
        store: PausedRunStore | None = None,
        dependency_key: str = "agui_tools",
    ) -> None:
        """Initialize the runner.

        Args:
            agent: The Agno agent. It **must** be built with
                ``tools=make_tools_factory(base_tools)`` and
                ``cache_callables=False`` — otherwise the frontend tools
                injected per-run won't reach the LLM.
            storage: Convenience: if provided and ``store`` is not, a
                :class:`PausedRunStore` is constructed automatically.
            store: Pre-built paused-run store. Wins over ``storage``.
            dependency_key: The Agno ``dependencies`` key under which the
                runner passes the per-run AG-UI tool list. Must match the
                key used by :func:`make_tools_factory`. Defaults to
                ``"agui_tools"``.

        Raises:
            ValueError: If neither ``storage`` nor ``store`` is provided.
        """
        if store is None:
            if storage is None:
                msg = "AgnoHitlRunner requires either `storage` or `store`."
                raise ValueError(msg)
            store = PausedRunStore(storage)
        self._agent = agent
        self._store = store
        self._dependency_key = dependency_key

    # ── Low-level: run / resume one Agno run ──────────────────────────────

    async def run(
        self,
        message: str,
        *,
        send: Callable[[BaseAgentRunEvent], Coroutine[Any, Any, None]],
        thread_id: str,
        agui_tools: list[AgUiTool] | None = None,
        images: list[Any] | None = None,
    ) -> PauseInfo | None:
        """Stream a fresh Agno run.

        Args:
            message: User prompt to send to the agent.
            send: Async callback invoked for each digitalkin event
                produced by :class:`AgnoStreamAdapter`. Typically maps
                through :meth:`AgUiMixin.send_message`.
            thread_id: AG-UI thread identifier (used as the paused-run
                storage key if the run pauses).
            agui_tools: Frontend tools declared by the AG-UI client for
                this run. Merged with the agent's base tools through the
                factory; ``None`` or empty is equivalent to "no frontend
                tools this turn".
            images: Optional multimodal inputs forwarded to Agno.

        Returns:
            ``None`` on normal completion. A :class:`PauseInfo` if the run
            paused on one or more external tool calls — the caller is
            responsible for emitting the awaiting ``RunFinished`` (use
            :func:`emit_awaiting_tool_result` or let
            :meth:`handle_agui_input` do it).
        """
        from agno.run.agent import RunOutput

        logger.info("AgnoHitlRunner.run: starting (thread_id=%s, msg_len=%d)", thread_id, len(message))

        stream = self._agent.arun(
            message,
            images=images,
            stream=True,
            stream_events=True,
            yield_run_output=True,
            dependencies={self._dependency_key: agui_tools or []},
        )
        return await self._drive(stream=stream, send=send, thread_id=thread_id, run_output_cls=RunOutput)

    async def continue_paused_run(
        self,
        thread_id: str,
        tool_results: dict[str, str],
        *,
        send: Callable[[BaseAgentRunEvent], Coroutine[Any, Any, None]],
        run_id: str | None = None,
        agui_tools: list[AgUiTool] | None = None,
    ) -> PauseInfo | None:
        """Resume a previously paused run.

        Loads the persisted :class:`~agno.run.agent.RunOutput`, injects
        the tool results into the matching
        :class:`~agno.run.requirement.RunRequirement` entries, and calls
        :meth:`~agno.agent.Agent.acontinue_run`. On normal completion the
        storage record is removed; on re-pause it is refreshed.

        Args:
            thread_id: AG-UI thread identifier (the storage key).
            tool_results: Mapping of ``tool_call_id`` → serialized result
                (typically a JSON string). Every pending tool must be
                resolved — unresolved requirements will stall the run.
            send: Digitalkin-event callback (same contract as :meth:`run`).
            run_id: AG-UI run identifier for this resume turn. Used to
                emit a synthetic ``RUN_STARTED`` before streaming — Agno
                emits ``RunContinued`` (not ``RunStarted``) on resume.
            agui_tools: Frontend tool definitions for the resumed run.
                The AG-UI client should re-send the same list it provided
                at the original turn so tool schemas stay registered.

        Returns:
            ``None`` on final completion. A fresh :class:`PauseInfo` when
            the resumed run paused again (cascading frontend tools). If
            no paused record exists for ``thread_id``, returns ``None``.
        """
        from agno.run.agent import RunOutput

        record = await self._store.load(thread_id)
        if record is None:
            logger.warning("continue_paused_run: no paused record for thread_id=%s", thread_id)
            return None

        run_output = RunOutput.from_dict(record.payload)
        logger.info(
            "continue_paused_run: resuming thread_id=%s run_id=%s with %d result(s)",
            thread_id,
            record.run_id,
            len(tool_results),
        )

        # AG-UI contract: every run must start with a RUN_STARTED event. Agno
        # emits RunContinued (not RunStarted) on acontinue_run, and the adapter
        # has no handler for it, so without this the front rejects with "First
        # event must be RUN_STARTED".
        from digitalkin.models.events import AgentRunEvent, RunStartedEvent

        await send(
            RunStartedEvent(
                event=AgentRunEvent.RUN_STARTED,
                run_id=run_id,
                thread_id=thread_id,
                timestamp=None,
                metadata=None,
            )
        )

        # Agno's _acontinue_run takes its tool state from `run_response.tools`
        # when a `run_response` is provided — the `updated_tools` /
        # `requirements` kwargs are only applied on the `run_id` code path
        # (agno/agent/_run.py:3618-3665). After a RunOutput round-trip through
        # to_dict/from_dict, `run_output.tools[i]` and `run_output.requirements
        # [i].tool_execution` are DIFFERENT ToolExecution instances, so using
        # set_external_execution_result on requirements mutates the wrong
        # objects. Fix: write results directly onto run_output.tools.
        for tool in run_output.tools or []:
            tid = getattr(tool, "tool_call_id", None)
            if tid and tid in tool_results:
                tool.result = tool_results[tid]

        # Keep requirements in sync for completeness (Agno doesn't read them
        # on the run_response path, but consistency is good for debugging).
        for req in run_output.requirements or []:
            tool_exec = req.tool_execution
            if (
                tool_exec is not None
                and getattr(req, "needs_external_execution", False)
                and tool_exec.tool_call_id in tool_results
            ):
                req.set_external_execution_result(tool_results[tool_exec.tool_call_id])

        stream = self._agent.acontinue_run(
            run_response=run_output,
            stream=True,
            stream_events=True,
            yield_run_output=True,
            dependencies={self._dependency_key: agui_tools or []},
        )
        pause_info = await self._drive(stream=stream, send=send, thread_id=thread_id, run_output_cls=RunOutput)

        if pause_info is None:
            await self._store.delete(thread_id)
            logger.info("continue_paused_run: thread_id=%s completed, record cleared", thread_id)
        return pause_info

    # ── Mid-level: resume detection ───────────────────────────────────────

    async def try_resume(
        self,
        input_data: Any,
        *,
        send: Callable[[BaseAgentRunEvent], Coroutine[Any, Any, None]],
    ) -> tuple[bool, PauseInfo | None]:
        """Try to resume a paused run from an AG-UI input.

        The ``input_data`` only needs to duck-type ``thread_id``,
        ``messages``, and ``tools`` (typically an ``AgUiStreamInput``).
        This method:

        1. Loads the paused record for ``input_data.thread_id``. Returns
           ``(False, None)`` if there is none.
        2. Looks for ``ToolMessage`` entries in ``input_data.messages``
           whose ``tool_call_id`` matches a pending one.
        3. If any match → dispatches :meth:`continue_paused_run` and
           returns ``(True, pause_info_or_none)``.
        4. If no match but the last message is a fresh ``UserMessage``,
           drops the stale record (HITL abandon) and returns
           ``(False, None)``.

        Returns:
            ``(resumed, pause_info)``:

            - ``(False, None)``: no resume, caller should run the
              fresh-message path.
            - ``(True, None)``: resume ran to normal completion.
            - ``(True, PauseInfo)``: resume paused again (cascading tools).
        """
        from ag_ui.core.types import ToolMessage, UserMessage

        thread_id = getattr(input_data, "thread_id", None)
        if not thread_id:
            return False, None

        record = await self._store.load(thread_id)
        if record is None:
            return False, None

        messages = getattr(input_data, "messages", None) or []
        pending = set(record.pending_tool_call_ids)

        tool_results: dict[str, str] = {}
        for msg in messages:
            if isinstance(msg, ToolMessage) and msg.tool_call_id in pending:
                tool_results[msg.tool_call_id] = msg.content

        if not tool_results:
            last = messages[-1] if messages else None
            if isinstance(last, UserMessage):
                logger.info(
                    "try_resume: dropping stale paused record for thread_id=%s (new user message)",
                    thread_id,
                )
                await self._store.delete(thread_id)
            return False, None

        # Partial resolution guard: Agno's acontinue_run expects ALL external
        # tool calls to have `.result` set. If we only received some, the
        # resume would raise "Tool X requires external execution, cannot
        # continue run". Emit a clear RUN_ERROR and keep the record so the
        # client can retry with all results in a single request.
        missing = pending - set(tool_results.keys())
        if missing:
            from digitalkin.models.events import AgentRunEvent, RunErrorEvent, RunStartedEvent

            input_run_id = getattr(input_data, "run_id", None)
            logger.warning(
                "try_resume: partial tool results for thread_id=%s — resolved %d/%d, missing=%s",
                thread_id,
                len(tool_results),
                len(pending),
                sorted(missing),
            )
            await send(
                RunStartedEvent(
                    event=AgentRunEvent.RUN_STARTED,
                    run_id=input_run_id,
                    thread_id=thread_id,
                    timestamp=None,
                    metadata=None,
                )
            )
            await send(
                RunErrorEvent(
                    event=AgentRunEvent.RUN_ERROR,
                    error_type="partial_tool_results",
                    content=(
                        f"Partial tool results: {len(tool_results)}/{len(pending)} "
                        f"resolved, missing {sorted(missing)}. The agent is paused on "
                        f"{len(pending)} frontend tool call(s); all pending ToolMessages "
                        "must be provided in a single RunAgentInput for the run to "
                        "resume. The paused state has been preserved — retry once all "
                        "tool results are available."
                    ),
                    error_details=None,
                    timestamp=None,
                    metadata=None,
                )
            )
            return True, None

        logger.info(
            "try_resume: resuming thread_id=%s with %d tool result(s)",
            thread_id,
            len(tool_results),
        )
        pause_info = await self.continue_paused_run(
            thread_id=thread_id,
            tool_results=tool_results,
            send=send,
            run_id=getattr(input_data, "run_id", None),
            agui_tools=getattr(input_data, "tools", None),
        )
        return True, pause_info

    # ── High-level: trigger entry point ──────────────────────────────────

    async def handle_agui_input(
        self,
        input_data: Any,
        *,
        send: Callable[[BaseAgentRunEvent], Coroutine[Any, Any, None]],
        context: ModuleContext | None = None,
        message: str | None = None,
        images: list[Any] | None = None,
    ) -> PauseInfo | None:
        """One-shot dispatch of an AG-UI ``RunAgentInput``.

        Handles the three cases in order:

        1. Resume a paused run if the input carries a matching
           ``ToolMessage`` (see :meth:`try_resume`).
        2. Drop a stale paused record if the input is a new
           ``UserMessage`` while a tool was pending (HITL abandon).
        3. Fresh run on the last ``UserMessage`` in ``input_data.messages``
           (or on the explicit ``message`` argument).

        When a run pauses (fresh or resumed) and ``context`` is provided,
        this method also emits the AG-UI ``RunFinished`` with
        ``status="awaiting_tool_result"`` via
        :func:`emit_awaiting_tool_result`. Pass ``context=None`` if you
        want to emit it yourself.

        Args:
            input_data: Any object with ``thread_id``, ``messages``, and
                ``tools`` attributes (typically an ``AgUiStreamInput``).
            send: Digitalkin-event callback (e.g. wrapping
                ``self.send_message(context, event)`` in a trigger).
            context: If provided, the awaiting ``RunFinished`` is emitted
                automatically on pause.
            message: Override the user prompt extraction. Normally left
                as ``None`` — the runner picks the last ``UserMessage``
                content from ``input_data.messages``.
            images: Optional multimodal inputs forwarded to Agno.

        Returns:
            ``None`` on normal completion (or when no actionable input
            was found). A :class:`PauseInfo` on pause (already emitted to
            the front if ``context`` was provided).
        """
        from ag_ui.core.types import UserMessage

        # 1. Resume path
        resumed, pause_info = await self.try_resume(input_data=input_data, send=send)
        if resumed:
            if pause_info is not None and context is not None:
                await emit_awaiting_tool_result(
                    context,
                    thread_id=pause_info.thread_id,
                    run_id=pause_info.run_id,
                    pending_tool_call_ids=pause_info.pending_tool_call_ids,
                )
            return pause_info

        # 2. Fresh run path
        if message is None:
            messages = getattr(input_data, "messages", None) or []
            user_messages = [m for m in messages if isinstance(m, UserMessage)]
            if not user_messages:
                logger.warning("handle_agui_input: no user message in input, nothing to do")
                return None
            content = user_messages[-1].content
            if isinstance(content, list):
                content = " ".join(getattr(p, "text", "") for p in content if hasattr(p, "text"))
            message = content

        pause_info = await self.run(
            message=message,
            send=send,
            thread_id=getattr(input_data, "thread_id", ""),
            agui_tools=getattr(input_data, "tools", None),
            images=images,
        )
        if pause_info is not None and context is not None:
            await emit_awaiting_tool_result(
                context,
                thread_id=pause_info.thread_id,
                run_id=pause_info.run_id,
                pending_tool_call_ids=pause_info.pending_tool_call_ids,
            )
        return pause_info

    # ── Internals ─────────────────────────────────────────────────────────

    async def _drive(
        self,
        *,
        stream: Any,
        send: Callable[[BaseAgentRunEvent], Coroutine[Any, Any, None]],
        thread_id: str,
        run_output_cls: type,
    ) -> PauseInfo | None:
        """Drain an Agno stream, forward events, detect pause, persist.

        Uses :class:`AgnoStreamAdapter` for event translation. The adapter
        already synthesizes tool-call events on ``run_paused`` (so the
        front sees the frontend tool call) and sets ``adapter.is_paused``
        — we just need to capture the final :class:`RunOutput`
        (from ``yield_run_output=True``) and hand it to the store.

        Returns:
            :class:`PauseInfo` when the stream paused, ``None`` otherwise.
        """
        from digitalkin.community.agno.agno_adapter import AgnoStreamAdapter

        adapter = AgnoStreamAdapter()
        final_run_output: RunOutput | None = None

        async for raw_event in stream:
            if isinstance(raw_event, run_output_cls):
                final_run_output = raw_event
                continue
            for event in adapter.to_digitalkin_events(raw_event):
                await send(event)

        for event in adapter.flush():
            await send(event)

        if adapter.is_paused and final_run_output is not None and getattr(final_run_output, "is_paused", False):
            pause_info = await self._store.save(run_output=final_run_output, thread_id=thread_id)
            # Attach the AG-UI-shaped messages that Agno built during this run
            # (notably the assistant message carrying `tool_calls`). The stream
            # events alone don't give the front a way to materialise this
            # message, so `handle_agui_input` will push it as a MessagesSnapshot.
            pause_info.new_messages = _agno_messages_to_agui(final_run_output.messages or [])
            return pause_info

        return None
