"""Models for the Agno community integration."""

from ag_ui.core.types import Message as AgUiMessage
from pydantic import BaseModel, Field


class PauseInfo(BaseModel):
    """Summary of a paused Agno run.

    Returned by :meth:`AgnoHitlRunner.run` and related methods whenever
    the run paused on one or more external tool calls. Callers typically
    use it to emit the AG-UI awaiting-tool-result event to the front.

    ``new_messages`` carries the AG-UI messages generated by Agno during
    the paused run (user echoes, the assistant message with ``tool_calls``,
    and any tool results emitted before the pause). It's provided because
    Agno does not emit stream events from which the front can reconstruct
    the assistant-with-tool-calls message — in particular, when the LLM
    goes straight from reasoning to a frontend tool call without emitting
    any text. Consumers typically push these messages to the front via a
    :class:`~ag_ui.core.events.MessagesSnapshotEvent` so the client has an
    authoritative view of the conversation.
    """

    thread_id: str
    run_id: str
    pending_tool_call_ids: list[str]
    new_messages: list[AgUiMessage] = Field(default_factory=list)
